al3wn/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users.views import register, career, profile, AllUsers

# Improving DJ Admin
admin.site.site_title = 'AM6 Site Admin'
admin.site.site_header = 'AM6 Administration'
admin.site.index_title = 'AM6 Administration'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('fb_bot/', include('fb_bot.urls')),
    path('', include('core.urls')),
    path('new/', include('reserve.urls')),
    path('report/', include('report.urls')),
    path('careers/', career, name='Career'),
    path('register/', register , name="Register"),
    path('u/<year>/', AllUsers.as_view()),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html') , name="Login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html') , name="Logout"),
    path('profile/', profile, name='Profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html') , name="Password Reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html') , name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html') , name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html') , name="password_reset_complete"),
    path('url/', include('shortner.urls')),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
# from django.conf.urls import handler404

from . import views

# handler404 = 'core.views.not_found'


urlpatterns  =  [
    path('', views.home, name='Home'),
    path('about/', views.about, name='About'),
    path('dev/', views.dev, name='Dev'),
    path('pricing/', views.price, name='Price'),
    path('dashboard/', views.dashboard, name='Dashboard'),
    path('sec/', views.sec, name='Secondary'),
    path('youtube/', views.youtube),
    path('stage1/', views.stage1, name="Stage1"),
    path('stage2/', views.stage2, name="Stage2"),
    path('birthdays/', views.Birthdays.as_view(), name='Birthday'),
    path('birthdays/<int:month>/<int:day>/', views.AllBirthdays.as_view(), name='AllBirthday'),
    # Deutsch Akademie
    path('HerrShady/', views.herr_shady, name="HerrShady"),
    path('HerrShady/Lesson/', views.shady_lesson, name='HerrShadyLesson'),
    path('HerrShady/1/', views.first_shady, name="HerrShady1"),
    path('HerrShady/2/', views.second_shady, name="HerrShady2"),
    path('HerrShady/3/', views.third_shady, name="HerrShady3"),
    # AliRashed
    path('HerrAliRashed/', views.herr_ali ,name='HerrAli'),
    path('HerrAliRashed/1/', views.first_ali ,name='HerrAli1'),
    path('HerrAliRashed/2/', views.second_ali ,name='HerrAli2'),
    path('HerrAliRashed/3/', views.third_ali ,name='HerrAli3'),
    # Mohamed Abdel Atty
    path('HerrM/', views.herr_m ,name='HerrM'),
    path('HerrM/1/', views.first_m ,name='HerrM1'),
    path('HerrM/2/', views.second_m ,name='HerrM2'),
    path('HerrM/3/', views.third_m ,name='HerrM3'),
    # Herr Khaled Bakheet
    path('HerrBakheet/', views.herr_bakheet ,name='HerrBakheet'),
    path('HerrBakheet/1/', views.first_bakheet ,name='HerrBakheet1'),
    path('HerrBakheet/2/', views.second_bakheet ,name='HerrBakheet2'),
    path('HerrBakheet/3/', views.third_bakheet ,name='HerrBakheet3'),
    # halem
    path('Halem/3/', views.third_halem, name="Halem3"),
    path('Halem/3/Lesson/', views.halem_lesson, name="HalemLesson"),
    # Bassem
    path('Bassem/1/', views.FirstBassem.as_view(),name='Bassem1'),
    path('Bassem/2/', views.SecondBassem.as_view() ,name='Bassem2'),
    path('Bassem/3/', views.ThirdBassem.as_view() ,name='Bassem3'),
    path('Bassem/up/', views.UpBassem.as_view(),name='BassemUp'),
    path('Bassem/perfect/', views.PerfectBassem.as_view(),name='BassemPerfect'),
    path('Bassem/innovate/', views.InnovateBassem.as_view(),name='BassemInnovate'),
    path('Bassem/read/', views.ReadBassem.as_view(),name='BassemRead'),
    path('Bassem/bank/', views.BankBassem.as_view(),name='BassemBank'),
    path("Bassem/videos/", views.VideosBassem.as_view(), name='BassemVideos'),
    path("Bassem/firsts/", views.firsts, name='BassemFirsts'),
    path("Bassem/firsts/01/", views.Firsts01.as_view(), name='BassemFirsts01'),
    path("Bassem/firsts/02/", views.Firsts02.as_view(), name='BassemFirsts02'),
    path("Bassem/youtube/", views.bassem_youtube, name='BassemYoutube'),
    # Ehab
    path('EhabElShafey/', views.ehab_elshafey ,name='Ehab'),
    path('Ehab/2/', views.second_ehab ,name='Ehab2'),
    path('Ehab/3/', views.third_ehab ,name='Ehab3'),
    path('ehab/3/', views.third_ehab_open, name='Ehab3Open'),
    # Anis Fawzy
    path('Anis/3/', views.third_Anis_Fawzy, name="Anis3"),
    # Ehab Gaber
    path('EhabGaber/3/', views.third_ehab_gaber, name="EhabGaber3")

]

users/models.py
import os
from django.db import models
from django.utils.html import mark_safe
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser

GENDER_CHOICE=(
	("Male","Male"),
	("Female","Female")
)

SCHOOL_YEAR = (
	('1', '1'),
	('2', '2'),
	('3', '3')
	)
POSITIONS_CHOICE = (
	('PR', "PR"),
	("Customer Service", "Customer Service"),
	("Graphic Designer", "Graphic Designer"),
	('technical support agent', 'technical support agent'),
	)

class User(AbstractUser):
	date_of_birth = models.DateField(_('date_of_birth'), blank=True, null=True)
	region = models.CharField(_('region'), blank=True, null=True, max_length=255)
	phone_number = models.FloatField(_('phone_number'))
	national_id = models.FloatField(_('national_id'), unique=True) 
	gender = models.CharField(_('gender'), choices=GENDER_CHOICE, max_length=255)
	year = models.CharField(_('year'), choices=SCHOOL_YEAR, max_length=255)
	is_student = models.BooleanField(_('is_student'), default=True)
	is_publisher = models.BooleanField(_('is_publisher'), default=False)

	def __str__(self):
		return self.username

	def pic(self):
		if self.profile.image == "default.jpg":
			return "No"
		else:
			return "Yes"

def get_upload_path(instance, filename):
    return os.path.join(
      'profile_pics', instance.user.gender, instance.user.username, filename)

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	image = models.ImageField(default='default.jpg', upload_to=get_upload_path)

	def __str__(self):
		return f'{self.user.username} Profile'

	def image_vertify(self):
		if self.image == "default.jpg":
			return "No"
		else:
			return "Yes"

	def image_tag(self):
		return mark_safe('<img src="%s" width="150" height="150" />' % (self.image.url))

	def thumb(self):
		return mark_safe('<img src="%s" style="width: 45px; height:45px;" />' % self.image.url)


	image_tag.short_description = 'Image'


def personal_image_upload_path(instance, filename):
    return os.path.join(
      'applicant_pics', instance.gender, instance.full_name, filename)

class Applicant(models.Model):
	full_name = models.CharField(_('Full Name'), max_length=255)
	personal_image = models.ImageField(upload_to='applicant_pics')
	date_of_birth = models.DateField(_('Date of Birth'))
	address = models.CharField(_('Address'), max_length=512)
	link = models.URLField(_('Link'), blank=True, null=True)
	phone_number = models.FloatField(_('Phone Number'))
	a_phone_number = models.FloatField(_('Phone Number (optional)'), blank=True, null=True)
	national_id = models.FloatField(_('National Id'), unique=True)
	available = models.BooleanField(_('Available for video interview'), default=False)
	college = models.CharField(_('College'), max_length=255)
	year = models.IntegerField(_('Academic Year'))
	gender = models.CharField(_('Gender'), choices=GENDER_CHOICE, max_length=255)
	why = models.TextField(_('Why Do you want to join us?'))
	how = models.TextField(_("How did you know about us"))
	what = models.TextField(_('What Skills do you have besides the requirements?'))
	position = models.CharField(_('Position'), choices=POSITIONS_CHOICE,
	 max_length=255)
	timestamp = models.DateTimeField(auto_now_add=True)
	email = models.EmailField()
	# Interview Stuff
	notes1 = models.TextField(_('The first interviewer notes'), blank=True, null=True)
	rating1 = models.IntegerField(_('The first interviewer notes (/10)'), blank=True, null=True)
	notes2 = models.TextField(_('The second interviewer notes'), blank=True, null=True)
	rating2 = models.IntegerField(_('The second interviewer notes (/10)'), blank=True, null=True)
	accepted = models.BooleanField(_('Accepted'), default=False)


	def __str__(self):
		return self.full_name

	def image_tag(self):
		return mark_safe('<img src="%s" width="150" height="150" />' % (self.personal_image.url))

	def thumb(self):
		return mark_safe('<img src="%s" style="width: 20px; height:20px;" />' % self.personal_image.url)

	image_tag.short_description = 'Image'


	

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _

from .models import Profile, Applicant

GENDER_CHOICE=(
	("Male",_("Male")),
	("Female",_("Female"))
)

SCHOOL_YEAR = (
	('1', '1'),
	('2', '2'),
	('3', '3')
	)

User = get_user_model()

class UserResgiterForm(UserCreationForm):
	region = forms.CharField(label=_('Region'))
	date_of_birth = forms.DateField(label=_('Date of Birth'),
		 widget=forms.TextInput(attrs={'type': 'date'}))       
	phone_number = forms.FloatField(label=_('Phone Number'),
	widget=forms.TextInput(attrs={'placeholder':'ex: 01553057088'}),
	max_value=1599999999, min_value=101111111)
	national_id = forms.FloatField(label=_('National ID'),
	widget=forms.TextInput(attrs={'placeholder':'ex: 30001011801881'}),
	max_value=99999999999999, min_value=10000000000000)
	gender = forms.ChoiceField(label=_('Gender'), choices=GENDER_CHOICE)
	year = forms.ChoiceField(label=_('Grade'), choices=SCHOOL_YEAR)
	email = forms.EmailField(label=_('E-mail'))
	last_name = forms.CharField(label=_('Last Name'))
	first_name = forms.CharField(label=_('First Name'))

	class Meta:
		model = User
		fields = ['first_name', 'last_name' ,'username', 'region', 'email', 'phone_number', 'date_of_birth', 'gender', 'national_id', 'year', 'password1', 'password2']



class UserUpdateForm(forms.ModelForm):
	region = forms.CharField(label=_('Region'))
	date_of_birth = forms.DateField(label=_('Date of Birth'),
		 widget=forms.TextInput(attrs={'type': 'date'}))       
	phone_number = forms.FloatField(label=_('Phone Number'),
	max_value=1599999999, min_value=101111111)
	national_id = forms.FloatField(label=_('National ID'),
	max_value=99999999999999, min_value=10000000000000)
	gender = forms.ChoiceField(label=_('Gender'), choices=GENDER_CHOICE)
	year = forms.ChoiceField(label=_('Grade'), choices=SCHOOL_YEAR)
	email = forms.EmailField()
	last_name = forms.CharField(label=_('Last Name'))
	first_name = forms.CharField(label=_('First Name'))

	class Meta:
		model = User
		fields = ['first_name', 'last_name' ,'username', 'region', 'email', 'phone_number', 'date_of_birth', 'gender', 'national_id', 'year']



class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['image']


class ApplicantForm(forms.ModelForm):
	date_of_birth = forms.DateField(label=_('Date of Birth'),
		 widget=forms.TextInput(attrs={'type': 'date'}))
	phone_number = forms.FloatField(label=_('Phone Number'),
	max_value=1599999999, min_value=101111111)
	national_id = forms.FloatField(label=_('National ID'),
	max_value=99999999999999, min_value=10000000000000)
	year = forms.FloatField(label=_('Academic Year'),
	max_value=10)
	how = forms.CharField(label=_("How did you know about us"),
		widget=forms.Textarea, min_length=20)
	what = forms.CharField(label=_('What Skills do you have besides the requirements?'),
		widget=forms.Textarea, min_length=20)
	why = forms.CharField(label=_('Why Do you want to join us?'),
		widget=forms.Textarea, min_length=20)
	link = forms.CharField(label=_("Online link for your work (Website/FB Page/behance...etc)"), required=False)
	class Meta:
		model = Applicant
		fields = ['full_name', 'email', 'date_of_birth',
		'gender','position', 'available', 'personal_image',
		'address', 'link' ,'phone_number','a_phone_number',
		'national_id', 'college', 'year',
		'how', 'what', 'why']

users/views.py
from django.contrib import messages
from django.views.generic import ListView
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext as _

from .forms import UserResgiterForm, UserUpdateForm, ProfileUpdateForm, ApplicantForm

from core.views import AdminRequiredMixin

User = get_user_model()

def register(request):
	if request.user.is_authenticated:
		messages.success(request, f'You already have an Account!')
		return redirect('Profile')
	else:
		if request.method == "POST":
			form = UserResgiterForm(request.POST)
			if form.is_valid():
				form.save()
				username = form.cleaned_data.get("username")
				messages.success(request, f'{username}, your account has been created! You can Log In')
				return redirect('Login')
		else:
			form = UserResgiterForm()
		return render(request, 'users/register.html', {'form' : form, 'title' : _('Register')})

	
@login_required
def profile(request):
	if request.method == "POST":
		user_form = UserUpdateForm(request.POST, instance=request.user)
		profile_form = ProfileUpdateForm(request.POST, request.FILES,instance=request.user.profile)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			messages.success(request, f'Your account has been Updated')
			return redirect('Profile')
	else:
		user_form = UserUpdateForm(instance=request.user)
		profile_form = ProfileUpdateForm(instance=request.user.profile)


	context = {
		'user_form': user_form,
		'profile_form': profile_form,
		'title' : request.user.username
	}
	return render(request, 'users/profile.html', context)

def career(request):
	if request.method == "POST":
		form = ApplicantForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			messages.success(request, f'Your data have been submitted😍! We will contact you💖')
			return redirect('Home')
	else:
		form = ApplicantForm()
	return render(request, 'users/career.html', {'form' : form, 'title' : _('Careers')})


class AllUsers(AdminRequiredMixin, ListView):
	template_name = 'core/birth.html'
	context_object_name = 'date'
	paginate_by = 12

	def get_queryset(self, **kwargs):
		return User.objects.all().filter(date_of_birth__year=str(self.kwargs['year']))

	def get_context_data(self, *args, **kwargs):
		context = super(AllUsers, self).get_context_data(*args, **kwargs)
		y = str(self.kwargs['year'])
		count = User.objects.all().filter(date_of_birth__year=str(self.kwargs['year'])).count()
		context['title'] = f"{y} Users"
		context['count'] = count
		return context

templates/users/career.html
{% extends "core/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<div class="wrap">
            <div class="row align-items-center justify-content-center mb-5">
                <h1>Careers</h1>
            </div>
            <div class="jobs">
                <div class="card job-card" id="PR">
                    <div class="job-card-title">
                        <p class="heading">Part time PR</p>
                    </div>
                    <p class="text-muted">You will be responsible for the communication<br>with our customers old or potential,<br>Face to face, Phone or online</p>
                    <ol class="list-group">
                        <li class="list-group-item"><b>Requirements</b></li>
                        <li class="list-group-item">1) Communication</li>
                        <li class="list-group-item">2) persuasion</li>
                        <li class="list-group-item">3) Patience</li>
                        <li class="list-group-item">4) On Time</li>
                        <li class="list-group-item">5) From Benha</li>
                      </ol>
                    <div class="row btnsubmit mt-4">
                        <div class="col-md-6 col-6"> <a class="btn btn-primary btn-lg" href="#Career"><span>Apply Now</span></a> </div>
                        <div class="col-md-6 col-6"> <button type="button" class="btn btn-dark btn-lg"><span>Message</span></button> </div>
                    </div>
                </div>
                <br><br>
                <div class="card job-card" id="Support">
                    <div class="job-card-title">
                        <p class="heading">Technical Support Agent</p>
                    </div>
                    <p class="text-muted">You will be responsible for the communication<br>with our users to solve any problem,<br>using whatsapp (Technical knowledge / background is a must)</p>
                    <ol class="list-group">
                        <li class="list-group-item"><b>Requirements</b></li>
                        <li class="list-group-item">1) Patience</li>
                        <li class="list-group-item">2) Calm</li>
                        <li class="list-group-item">3) Great listener</li>
                        <li class="list-group-item">4) Always online</li>
                        <li class="list-group-item">5) From Benha</li>
                      </ol>
                    <div class="row btnsubmit mt-4">
                        <div class="col-md-6 col-6"> <a class="btn btn-primary btn-lg" href="#Career"><span>Apply Now</span></a> </div>
                        <div class="col-md-6 col-6"> <button type="button" class="btn btn-dark btn-lg"><span>Message</span></button> </div>
                    </div>
                </div>
                <br><br>
                <div class="card job-card" id="Designer">
                    <div class="job-card-title">
                        <p class="heading">Graphic Designer</p>
                    </div>
                    <p class="text-muted">You will be responsible for making the designs<br>that our users wants <a href="https://discord.gg/MafTjQamaS">(Click here to join)</a>,<br>using his/her knowledge</p>
                    <ol class="list-group">
                        <li class="list-group-item"><b>Requirements</b></li>
                        <li class="list-group-item">1) Patience</li>
                        <li class="list-group-item">2) Committed</li>
                        <li class="list-group-item">3) have knowledge of Discord</li>
                        <li class="list-group-item">4) Photoshop</li>
                        <li class="list-group-item">5) Illustrator</li>
                      </ol>
                    <div class="row btnsubmit mt-4">
                        <div class="col-md-6 col-6"> <a class="btn btn-primary btn-lg" href="#Career"><span>Apply Now</span></a> </div>
                        <div class="col-md-6 col-6"> <button type="button" class="btn btn-dark btn-lg"><span>Message</span></button> </div>
                    </div>
                </div>
            </div>
            <form class="form validate-form" id="Career" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <span class="form-title">
                    {% translate "Join Now" %} ✅
                </span>
                <legend class="border-bottom mb-4"><small class="text-muted">{% translate "(This will take no more than 4 minute to fill out💪✅🔥)" %}</small></legend>
                {{ form|crispy }}
<!--                 <div class="wrap-input validate-input" data-validate="Name is required">
                    <span class="label-input">Your Name*</span>
                    <input class="input" type="text" name="name" placeholder="Enter your name">
                    <span class="focus-input"></span>
                </div>
                <br><hr>

                <div class="wrap-input validate-input" data-validate="Valid email is required: ex@abc.xyz">
                    <span class="label-input">Email*</span>
                    <input class="input" type="text" name="email" placeholder="Enter your email addess">
                    <span class="focus-input"></span>
                </div>
                <div class="wrap-input input-select">
                    <span class="label-input">Gender*</span>
                    <div>
                        <select class="selection-2" name="gender">
                            <option value="male">Male</option>
                            <option value="female">Female</option>
                        </select>
                    </div>
                    <span class="focus-input"></span>
                </div>
                <div class="wrap-input validate-input" data-validate="Address is required">
                    <span class="label-input">Address*</span>
                    <input class="input" type="text" name="address" placeholder="Enter your address">
                    <span class="focus-input"></span>
                </div>
                <div class="wrap-input validate-input" data-validate="Phone number is required">
                    <span class="label-input">Phone*</span>
                    <input class="input" type="text" name="phone" placeholder="Enter your phone number">
                    <span class="focus-input"></span>
                </div>
                <div class="wrap-input validate-input" data-validate="National ID is required">
                    <span class="label-input">National ID*</span>
                    <input class="input" type="text" name="national" placeholder="Enter your national id">
                    <span class="focus-input"></span>
                </div>
                <div class="wrap-input validate-input" data-validate="College name is required">
                    <span class="label-input">College*</span>
                    <input class="input" type="text" name="college" placeholder="Enter your college name">
                    <span class="focus-input"></span>
                </div>
                <div class="wrap-input validate-input" data-validate="Academic Year is required">
                    <span class="label-input">Academic Year*</span>
                    <input class="input" type="text" name="year" placeholder="Enter the year">
                    <span class="focus-input"></span>
                </div>
                <div class="wrap-input input-select">
                    <span class="label-input">Position*</span>
                    <div>
                        <select class="selection-2" name="position">
                            <option value="pr">PR</option>
                        </select>
                    </div>
                    <span class="focus-input"></span>
                </div>
                <div class="form-group">
                    <div id="div_id_available" class="form-check">
                        <input type="checkbox" name="available" class="checkboxinput form-check-input"
                            id="id_available">
                        <label for="id_available" class="form-check-label"> Available for video interview </label>
                    </div>
                </div>
                <div id="div_id_personal_image" class="form-group"> 
                    <label for="id_personal_image" class="requiredField">
                        Personal image*
                    </label>
                    <div> 
                        <input type="file" name="personal_image" accept="image/*"
                            class="clearablefileinput form-control-file" required id="id_personal_image"> 
                    </div>
                </div>
                <div class="wrap-input validate-input" data-validate="Message is required">
                    <span class="label-input">How did you know about us*</span>
                    <textarea class="input" name="about" placeholder="Your message here..."></textarea>
                    <span class="focus-input"></span>
                </div>
                <div class="wrap-input validate-input" data-validate="Message is required">
                    <span class="label-input">What Skills do you have?*</span>
                    <textarea class="input" name="skills" placeholder="Your message here..."></textarea>
                    <span class="focus-input"></span>
                </div>
                <div class="wrap-input validate-input" data-validate="Message is required">
                    <span class="label-input">Why Do you want to join us?*</span>
                    <textarea class="input" name="join" placeholder="Your message here..."></textarea>
                    <span class="focus-input"></span>
                </div> -->
                <div class="container-form-btn">
                    <div class="wrap-form-btn">
                        <div class="form-bgbtn"></div>
                        <button class="form-btn" type="submit">
                            <span>
                                {% translate "Send" %}
                                <i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
                            </span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div id="dropDownSelect1"></div>	
{% endblock content %}

templates/users/login.html
{% extends "core/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<br>
<section class="intro">
	<div class="container">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">{% translate "Log In" %}</legend>
				{{ form|crispy }}
				<button class="btn btn-outline-info" type="submit">{% translate "Log In" %}</button>
				<small class='text-muted ml-2'>
					<a href="{% url 'Password Reset' %}">{% translate "Forget Password" %}?</a>
				</small>
			</fieldset>
			<div class="border-top pt-3">
				<small class="text-muted">{% translate "Do Not have an Account?" %} <a class="ml-2" href="{% url 'Register' %}">{% translate "Sign Up" %}</a></small>
			</div>
		</form>
	</div>
</section>
{% endblock content %}

templates/users/logout.html
{% extends "core/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<br>
<section class="intro">
	<div class="container">
      <section class="mb-4">
        <div class="row wow fadeIn">
          <div class='col-6 offset-3'>
            <br>
            <h1>{% trans "Sign Out" %}</h1>

            <p>{% trans 'You have signed out' %}</p>

          </div>
        </div>
      </section>
    </div>
    <br>
</section>
{% endblock content %}

templates/users/password_reset.html
{% extends "core/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<br>
<section class="intro">
	<div class="container">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">{% translate "Reset Password" %}</legend>
				{{ form|crispy }}
				<button class="btn btn-outline-info" type="submit">{% translate "Request Password Reset" %}</button>
			</fieldset>
		</form>
	</div>
</section>
{% endblock content %}

templates/users/password_reset_complete.html
{% extends "core/base.html" %}
{% load i18n %}

{% block content %}
<br>
<section class="intro">
	<div class="container">
      <section class="mb-4">
        <div class="row wow fadeIn">
          <div class='col-6 offset-3'>
            <br>
            <h3>{% trans "Your Password has been set" %}</h3>
            <div class="border-top pt-3">
              <small class="text-muted"> <a class="ml-2" href="{% url 'Login' %}">{% translate "Sign In" %}</a></small>
            </div>
          </div>
        </div>
      </section>
    </div>
    <br>
</section>
{% endblock content %}

templates/users/password_reset_confirm.html
{% extends "core/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<br>
<section class="intro">
	<div class="container">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">{% translate "Reset Password" %}</legend>
				{{ form|crispy }}
				<button class="btn btn-outline-info" type="submit">{% translate "Reset Password" %}</button>
			</fieldset>
		</form>
	</div>
</section>
{% endblock content %}

templates/users/password_reset_done.html
{% extends "core/base.html" %}
{% load i18n %}
{% block content %}
<br>
<section class="intro">
	<div class="container">
      <section class="mb-4">
        <div class="row wow fadeIn">
          <div class='col-6 offset-3'>
            <br>
            <h3>{% trans "An email has been sent with instructions to reset your password" %}</h3>
          </div>
        </div>
      </section>
    </div>
    <br>
</section>
{% endblock content %}

templates/users/register.html
{% extends "core/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<br>
<section style=" padding: 100px 0px 0px 0px">
	<div class="container">
		<h3>{% translate "How to" %} {% translate "Join Now" %} 💪🔥⏬</h3>
		<iframe width=100% height=300px src="https://www.youtube.com/embed/xbVo-jpgHXs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
</section>
<section class="intro">
	<div class="container">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">{% translate "Join Now" %} 😊💖✅</legend>
				{{ form|crispy }}
				<button class="btn btn-outline-info" type="submit">{% translate "Sign Up" %}</button>
			</fieldset>
			<div class="border-top pt-3">
				<small class="text-muted">{% translate "Alerady have an Acoount?" %} <a class="ml-2" href="{% url 'Login' %}">{% translate "Sign In" %}</a></small>
			</div>
		</form>
	</div>
</section>	
{% endblock content %}